### ISSUE TITLE
Crash on al::FBO::bind

### ISSUE THREAD

**Issue by mantaraya36** [AlloSphere-Research-Group/allolib#3]
#0  0x0000000000000000 in ?? ()
#1  0x000000000051c06a in al::FBO::bind (fboID=0) at /home/sphere/Code/allolib/src/core/graphics/al_FBO.cpp:127
#2  0x00000000004ca921 in al::RenderManager::framebuffer (id=0)
    at /home/sphere/Code/allolib/src/core/graphics/al_RenderManager.cpp:101
#3  0x00000000004a53fa in al::App::preOnDraw (this=0x7fffffffd6a0)
    at /home/sphere/Code/allolib/cmake/single_file/../../include/al/core/app/al_App.hpp:78
#4  0x00000000004a55cc in al::App::loop (this=0x7fffffffd6a0)
    at /home/sphere/Code/allolib/cmake/single_file/../../include/al/core/app/al_App.hpp:106
#5  0x00000000004a5693 in al::App::start (this=0x7fffffffd6a0)
    at /home/sphere/Code/allolib/cmake/single_file/../../include/al/core/app/al_App.hpp:121
#6  0x00000000004a41f6 in main () at /home/sphere/Code/allolib/examples/graphics/platonics.cpp:106

This is on:
Linux spherez05 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

However on my Ubuntu laptop that has version 17.10, things work fine...

**Comment by mantaraya36** [comment]
This was due to hardware failure. Nothing wrong with allolib
